import Head from "next/head";
import { AppContent } from "../components/pages/app";
import Text from "../components/customs/Text";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContent>
        <Text fSize={40} fWeight={900} tSpacing={0.5} lHeight={20}>
          Hello World!!!
        </Text>
      </AppContent>
    </div>
  );
}
